## Scrapeo de Documentos 23-F

In [1]:
import requests
from lxml import html
from tqdm import tqdm
import pandas as pd
import os
import hashlib

BASE = "https://23fbuscador.rtve.es"
headers = {"User-Agent": "Mozilla/5.0"}


# -----------------------------
# Helper: Get total number of pages
# -----------------------------
def get_total_pages():
    r = requests.get(f"{BASE}/?page_size=200&page=1", headers=headers)
    tree = html.fromstring(r.content)

    text = tree.xpath("//span[@class='nav-position']/text()")
    if not text:
        return 1

    # Example: "Página 1 de 7"
    parts = text[0].split()
    return int(parts[-1])


# -----------------------------
# Helper: Extract document rows from a listing page
# -----------------------------
def get_page_documents(page_number):
    url = f"{BASE}/?page_size=200&page={page_number}"
    r = requests.get(url, headers=headers)
    tree = html.fromstring(r.content)

    rows = tree.xpath("//table/tbody/tr")

    docs = []
    for row in rows:
        title = row.xpath(".//td[1]/a/text()")
        href = row.xpath(".//td[1]/a/@href")
        pages = row.xpath(".//td[2]/text()")
        summary = row.xpath(".//td[4]/text()")
        tags = row.xpath(".//td[5]//span[@class='tag-chip']/text()")

        if not href:
            continue

        docs.append({
            "title": title[0].strip() if title else "",
            "url": BASE + href[0],
            "pages": pages[0].strip() if pages else None,
            "summary": summary[0].strip() if summary else "",
            "tags": tags,
        })

    return docs


# -----------------------------
# Helper: Download transcript text from a document page
# -----------------------------
def download_transcript(url):
    r = requests.get(url, headers=headers)
    tree = html.fromstring(r.content)

    pre = tree.xpath("//pre/text()")
    if not pre:
        return None

    return pre[0]


# -----------------------------
# Helper: Generate safe filename
# -----------------------------
def make_safe_filename(title):
    # Remove illegal characters
    cleaned = "".join(c for c in title if c.isalnum() or c in " _-").strip()

    # If too long, shorten and add a hash
    if len(cleaned) > 100:
        hash_suffix = hashlib.md5(cleaned.encode()).hexdigest()[:8]
        cleaned = cleaned[:80] + "_" + hash_suffix

    return cleaned + ".txt"


# -----------------------------
# Main scraper
# -----------------------------
def scrape_all():
    os.makedirs("transcripts", exist_ok=True)

    total_pages = get_total_pages()
    print(f"Total pages: {total_pages}")

    all_docs = []

    # Step 1: Collect metadata for all documents
    for page in range(1, total_pages + 1):
        docs = get_page_documents(page)
        all_docs.extend(docs)

    print(f"Found {len(all_docs)} documents")

    # Step 2: Download transcripts + save .txt files
    for doc in tqdm(all_docs):
        transcript = download_transcript(doc["url"])
        doc["transcript"] = transcript

        if transcript:
            filename = make_safe_filename(doc["title"])
            filepath = os.path.join("transcripts", filename)

            with open(filepath, "w", encoding="utf-8") as f:
                f.write(transcript)

            doc["filename"] = filename
        else:
            doc["filename"] = None

    # Step 3: Convert to DataFrame
    df = pd.DataFrame(all_docs)
    df.to_csv("23f_scrappedDF.csv", index=False, encoding="utf-8")
    return df

In [2]:
# Run scraper
df = scrape_all()

Total pages: 1
Found 167 documents

100%|██████████| 167/167 [01:30<00:00,  1.85it/s]

In [3]:
df.head(5)

,title,url,pages,summary,tags,transcript,filename
0,Vista oral 2/81 del Consejo Supremo de Justici...,https://23fbuscador.rtve.es/document/ocr/1860?...,3,El juicio oral 2/81 celebrado en febrero de 19...,"[C/SG/2820/20-02-82, DTOR., Vista oral 2/81]",C/SG/2820/20-02-82\nDTOR.\n\nNOTA INFORMATIVA\...,Vista oral 281 del Consejo Supremo de Justicia...
1,Vista oral 2/81 del Consejo Supremo de Justici...,https://23fbuscador.rtve.es/document/ocr/1859?...,4,Resumen global del documento:\n\nEl documento ...,"[C/SG/2896/22-02-82, Vista oral 2/81, Consejo ...",C/SG/2896/22-02-82\n\n# NOTA INFORMATIVA\n\nAS...,Vista oral 281 del Consejo Supremo de Justicia...
2,Vista oral 2/81 del Consejo Supremo de Justici...,https://23fbuscador.rtve.es/document/ocr/1858?...,5,Resumen global del documento:\n\nEl documento ...,"[C/SG/2992/24-02-82, Vista Oral 2/81, Consejo ...",C/SG/2992/24-02-82\n\n# NOTA INFORMATIVA\n\nAS...,Vista oral 281 del Consejo Supremo de Justicia...
3,Vista oral 2/81 del Consejo Supremo de Justici...,https://23fbuscador.rtve.es/document/ocr/1857?...,6,El documento recoge el desarrollo de la sesión...,"[C/SG/3.081/25-02-82, Vista Oral 2/81, Consejo...",C/SG/3.081/25-02-82\n\n# NOTA INFORMATIVA\n\nA...,Vista oral 281 del Consejo Supremo de Justicia...
4,Vista oral 2/81 del Consejo Supremo de Justici...,https://23fbuscador.rtve.es/document/ocr/1856?...,6,Resumen global del documento sobre la sesión d...,"[C/SG/3.249/26-02-82, SG, Consejo Supremo de J...",C/SG/3.249/26-02-82\nSG\n\n# NOTA INFORMATIVA\...,Vista oral 281 del Consejo Supremo de Justicia...

In [9]:
from tabulate import tabulate
print(tabulate(df.head(1), headers='keys', tablefmt='psql'))

+----+----------------------------------------------------------------------------------+--------------------------------------------------------------------+---------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------+
|    | title                                                                            | url                                                                |   pages | summary                                                                                                                                                                                                                                                                                                         | tags                                               | transcript                                                                                                                                                                                                                                                                                                                                                                                  | filename                                                                         |
|----+----------------------------------------------------------------------------------+--------------------------------------------------------------------+---------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------|
|  0 | Vista oral 2/81 del Consejo Supremo de Justicia Militar (20 de febrero de 1982). | https://23fbuscador.rtve.es/document/ocr/1860?page_size=200&page=1 |       3 | El juicio oral 2/81 celebrado en febrero de 1982 se caracterizó por un intenso desarrollo en sus primeras sesiones, con declaraciones parciales de altos mandos militares y certificaciones oficiales, aunque plagado de controversias por la interpretación y selección de testimonios, especialmente en re... | ['C/SG/2820/20-02-82', 'DTOR.', 'Vista oral 2/81'] | C/SG/2820/20-02-82                                                                                                                                                                                                                                                                                                                                                                          | Vista oral 281 del Consejo Supremo de Justicia Militar 20 de febrero de 1982.txt |
|    |                                                                                  |                                                                    |         |                                                                                                                                                                                                                                                                                                                 |                                                    | DTOR.                                                                                                                                                                                                                                                                                                                                                                                       |                                                                                  |
|    |                                                                                  |                                                                    |         |                                                                                                                                                                                                                                                                                                                 |                                                    |                                                                                                                                                                                                                                                                                                                                                                                             |                                                                                  |
|    |                                                                                  |                                                                    |         |                                                                                                                                                                                                                                                                                                                 |                                                    | NOTA INFORMATIVA                                                                                                                                                                                                                                                                                                                                                                            |                                                                                  |
|    |                                                                                  |                                                                    |         |                                                                                                                                                                                                                                                                                                                 |                                                    |                                                                                                                                                                                                                                                                                                                                                                                             |                                                                                  |
|    |                                                                                  |                                                                    |         |                                                                                                                                                                                                                                                                                                                 |                                                    | ASUNTO: Vista oral 2/81                                                                                                                                                                                                                                                                                                                                                                     |                                                                                  |
|    |                                                                                  |                                                                    |         |                                                                                                                                                                                                                                                                                                                 |                                                    |                                                                                                                                                                                                                                                                                                                                                                                             |                                                                                  |
|    |                                                                                  |                                                                    |         |                                                                                                                                                                                                                                                                                                                 |                                                    | 1.- DESARROLLO DE LA SESIÓN CORRESPONDIENTE AL 20-02-82                                                                                                                                                                                                                                                                                                                                     |                                                                                  |
|    |                                                                                  |                                                                    |         |                                                                                                                                                                                                                                                                                                                 |                                                    |                                                                                                                                                                                                                                                                                                                                                                                             |                                                                                  |
|    |                                                                                  |                                                                    |         |                                                                                                                                                                                                                                                                                                                 |                                                    | - Solo ha tenido lugar la sesión de la mañana. Empezó a las 10,06 horas.                                                                                                                                                                                                                                                                                                                    |                                                                                  |
|    |                                                                                  |                                                                    |         |                                                                                                                                                                                                                                                                                                                 |                                                    |                                                                                                                                                                                                                                                                                                                                                                                             |                                                                                  |
|    |                                                                                  |                                                                    |         |                                                                                                                                                                                                                                                                                                                 |                                                    | - Durante la sesión han tenido lugar, a petición del Sr. Fiscal las declaraciones siguientes:                                                                                                                                                                                                                                                                                               |                                                                                  |
|    |                                                                                  |                                                                    |         |                                                                                                                                                                                                                                                                                                                 |                                                    |                                                                                                                                                                                                                                                                                                                                                                                             |                                                                                  |
|    |                                                                                  |                                                                    |         |                                                                                                                                                                                                                                                                                                                 |                                                    | . Parcial de Teniente Coronel D. Luis Arana Lorite (Ayte. Gral. Lluch).                                                                                                                                                                                                                                                                                                                     |                                                                                  |
|    |                                                                                  |                                                                    |         |                                                                                                                                                                                                                                                                                                                 |                                                    |                                                                                                                                                                                                                                                                                                                                                                                             |                                                                                  |
|    |                                                                                  |                                                                    |         |                                                                                                                                                                                                                                                                                                                 |                                                    | . Parcial de Teniente Coronel D. Manuel Miler Hidalgo (Ayte. Gral. Esquivias).                                                                                                                                                                                                                                                                                                              |                                                                                  |
|    |                                                                                  |                                                                    |         |                                                                                                                                                                                                                                                                                                                 |                                                    |                                                                                                                                                                                                                                                                                                                                                                                             |                                                                                  |


## Carga de Archivo Scrapeado

In [ ]:
from google.colab import files
files.upload()

Saving 23f_scrappedDF.csv to 23f_scrappedDF (1).csv

{'23f_scrappedDF (1).csv': b'title,url,pages,summary,tags,transcript,filename\nVista oral 2/81 del Consejo Supremo de Justicia Militar (20 de febrero de 1982).,https://23fbuscador.rtve.es/document/ocr/1860?page_size=200&page=1,3,"El juicio oral 2/81 celebrado en febrero de 1982 se caracteriz\xc3\xb3 por un intenso desarrollo en sus primeras sesiones, con declaraciones parciales de altos mandos militares y certificaciones oficiales, aunque plagado de controversias por la interpretaci\xc3\xb3n y selecci\xc3\xb3n de testimonios, especialmente en re...","[\'C/SG/2820/20-02-82\', \'DTOR.\', \'Vista oral 2/81\']","C/SG/2820/20-02-82\nDTOR.\n\nNOTA INFORMATIVA\n\nASUNTO: Vista oral 2/81\n\n1.- DESARROLLO DE LA SESI\xc3\x93N CORRESPONDIENTE AL 20-02-82\n\n- Solo ha tenido lugar la sesi\xc3\xb3n de la ma\xc3\xb1ana. Empez\xc3\xb3 a las 10,06 horas.\n\n- Durante la sesi\xc3\xb3n han tenido lugar, a petici\xc3\xb3n del Sr. Fiscal las declaraciones siguientes:\n\n. Parcial de Teniente Coronel D. Luis Arana Lorite (Ayte. Gral. Lluch).\n\n. Parcial de Teniente Coronel D. Manuel Miler Hidalgo (Ayte. Gral. Esquivias).\n\n. 1\xc2\xaa, 2\xc2\xaa, 3\xc2\xaa y 4\xc2\xaa del Teniente Coronel TEJERO.\n\n. Careo Teniente Coronel TEJERO - SR. CARRES.\n\n- Descanso de 11,50 horas a 12,13 horas.\n\n. Careo Teniente Coronel TEJERO - Capit\xc3\xa1n GOMEZ IGLESIAS\n\n. Certificaci\xc3\xb3n del Presidente del Congreso Sr. LAVILLA.\n\n. Certificaci\xc3\xb3n sobre la situaci\xc3\xb3n militar del TCOL.TEJERO.\n\n. 1\xc2\xaa y 3\xc2\xaa del Coronel D. DIEGO IBA\xc3\x91EZ INGLES\n\n. Certificaci\xc3\xb3n del entonces Gobernador Civil de Valencia D.Jos\xc3\xa9 Mar\xc3\xada Fern\xc3\xa1ndez del Rio Fern\xc3\xa1ndez\n\n. 1\xc2\xaa y 3\xc2\xaa del Teniente Coronel MAS OLIVER.\n\nLa vista se interrumpi\xc3\xb3 hasta las 10,00 horas del lunes d\xc3\xada 22-02-82.\n\n-1-\n\n./.\n\n2.- INCIDENCIAS E IMPRESIONES EN TORNO AL DESARROLLO DE LA SESION.\n\n- Al finalizar la lectura de la segunda declaraci\xc3\xb3n del Coronel Iba\xc3\xb1ez el defensor del Gral. Armada hizo notar que se hab\xc3\xada omitido parte de la declaraci\xc3\xb3n; el presidente accedi\xc3\xb3 a que se leyera lo omitido.\n\n- El fiscal contin\xc3\xbaa pidiendo se lean declaraciones parciales. Al parecer exist\xc3\xada un acuerdo informal de la SALA para permitir la lectura parcial de diligencias, as\xc3\xad como no solicitar la lectura de declaraciones de personas citadas como testigos a la vista oral.\n\nEste \xc3\xbaltimo aspecto fu\xc3\xa9 roto ayer por el Sr. Fiscal.\n\n- Uno de los defensores manifiesta que hab\xc3\xadan llegado a una ""especie de acuerdo"", antes de comenzar la vista, seg\xc3\xban el cual ni el Ministerio Fiscal ni los defensores iban a pedir excesivas lecturas de declaraciones. Sin embargo la l\xc3\xadnea del Fiscal est\xc3\xa1 alargando de manera muy notable \xc3\xa9sta fase inicial de la vista; puede dar lugar adem\xc3\xa1s a que algunos defensores hagan lo mismo.\n\n- Reticencias y sonrisas de defensores y codefensores al leer se las declaraciones:\n\n. Gobernador Civil de Valencia\n. Teniente Coronel Tejero\n\n- Contin\xc3\xbaa invoc\xc3\xa1ndose el protagonismo del REY y paralelamente el de la REINA; se afirma ten\xc3\xadan conocimiento de lo que se propon\xc3\xadan realizar los procesados. La lectura de declaraciones de algunos procesados hace que el nombre de Su Majestad est\xc3\xa9 presente de modo continuado. En quienes no tengan un juicio formado al respecto, introduce la duda en torno a la conducta del REY.\n\n-2-\n./.\n\n- El CESID permanece en primera fila de declaraciones, con una nueva figura: el SECTOR DE VALENCIA.\nEn la cuarta declaraci\xc3\xb3n del Teniente Coronel TEJERO afirma que hab\xc3\xada m\xc3\xa1s personas del CESID implicadas.\n\n3.- OTRAS INFORMACIONES DE CARACTER GENERAL\n- Los familiares v\xc3\xa1n tomando m\xc3\xa1s actividad y se acercan m\xc3\xa1s a las primeras filas. Tambi\xc3\xa9n realizan gestos y comentarios.\n- Comentario entre letrados invitados sobre que est\xc3\xa1 perfilada una misma l\xc3\xadnea defensiva que comprende al Gral. Armada, Cte. Cortina y Cap. G\xc3\xb3mez Igl\xc3\xa9sias.\n- Menor asistencia de invitados (Periodistas, familiares y asimismo militares).\n\nPRENSA:\n- Desde Barcelona ha llamado LA VANGUARDIA a la sala de prensa requiriendo informaci\xc3\xb3n sobre qu\xc3\xa9 decisi\xc3\xb3n se adoptar\xc3\xa1 en relaci\xc3\xb3n a los documentos que, al parecer, tiene el editor LARA (Supuesta maleta del Cap. S\xc3\xa1nchez Valiente).\n\nSEGURIDAD INTERIOR:\n- La salida de los procesados al finalizar cada sesi\xc3\xb3n, se ve alterada por la presencia de familiares y periodistas. Esta circunstancia, que puede dar lugar a incidentes, deber\xc3\xada ser evitada.\n\nSEGURIDAD EXTERIOR:\n- Menos efectivos que en el d\xc3\xada de ayer, al menos aparentemente, a lo largo del itinerario. Esta circunstancia se ha visto agravada por la no presencia de la Guardia Civil de Tr\xc3\xa1fico regulando la circulaci\xc3\xb3n en sem\xc3\xa1foros y giros obligados, sobre todo en la zona de Aluche a caballo sobre la carretera de Extremadura.",Vista oral 281 del Consejo Supremo de Justicia Militar 20 de febrero de 1982.txt\nVista oral 2/81 del Consejo Supremo de Justicia Militar (22 de febrero de 1982).,https://23fbuscador.rtve.es/document/ocr/1859?page_size=200&page=1,4,"Resumen global del documento:\n\nEl documento recoge el desarrollo de una serie de sesiones celebradas el 22 de febrero de 1982 por el Consejo Supremo de Justicia Militar, donde se analizaron declaraciones y diligencias relacionadas con hechos militares y posibles conspiraciones. A lo largo de las ses...","[\'C/SG/2896/22-02-82\', \'Vista oral 2/81\', \'Consejo Supremo de Justicia Militar\']","C/SG/2896/22-02-82\n\n# NOTA INFORMATIVA\n\nASUNTO: Vista oral 2/81. del Consejo Supremo de Justicia Militar.\n\n1.- DESARROLLO DE LA SESION CORRESPONDIENTE AL 22-02-82.\n\n- A las 10\'05 se inicia la sesi\xc3\xb3n, con una presencia menor de periodistas y familiares.\n\n- El Ministerio Fiscal solicita la lectura de:\n- Diligencia careo del Teniente Coronel Inf. D. Pedro MAS OLIVER con el Sr. CARRES.\n- Declaraci\xc3\xb3n del Comandante de Infanter\xc3\xada D. Jos\xc3\xa9 CORTINA --- PRIETO.\n- Diligencia de careo entre el Comandante CORTINA y el Teniente Coronel TEJERO.\n- Primera declaraci\xc3\xb3n del Capit\xc3\xa1n de la Guardia Civil D. Vicente GOMEZ IGLESIAS.\n- Oficio relativo a entrada y salida del coche del Capit\xc3\xa1n --- IGLESIAS el 23-F.\n- Primera declaraci\xc3\xb3n del General TORRES ROJAS.\n- Declaraci\xc3\xb3n idagatoria del General TORRES ROJAS.\n- Tercera declaraci\xc3\xb3n del General TORRES ROJAS.\n- Primera declaraci\xc3\xb3n del Comandante de Infanter\xc3\xada D. Ricardo PARDO ZANCADA.\n- Declaraci\xc3\xb3n indagatoria del Comandante PARDO.\n- Manifiesto dado en el Congreso.\n- Tercera declaraci\xc3\xb3n del Comandante PARDO.\n\n- A las 12\'09 el PRESIDENTE DEL CONSEJO suspende la vista.\n- A las 12\'35 se reanuda la vista.\n\n- El Ministerio Fiscal solicita la lectura de:\n- Cuarta declaraci\xc3\xb3n del Comandante PARDO.\n- Quinta declaraci\xc3\xb3n del Comandante PARDO.\n- Primera declaraci\xc3\xb3n del Capit\xc3\xa1n de Artiller\xc3\xada D. Joaquin TAMARIT NAVA.\n\n...//...\n\n- 2 -\n\n- Primera declaraci\xc3\xb3n del Coronel de Artiller\xc3\xada D. Jos\xc3\xa9 J. SAN MARTIN LOPEZ.\n- Tercera declaraci\xc3\xb3n del Coronel SAN MARTIN.\n- Primera declaraci\xc3\xb3n del Capit\xc3\xa1n de Artiller\xc3\xada D. Juan BATISTA GONZALEZ.\n\n- A las 14\'05 el PRESIDENTE DEL CONSEJO suspende la vista hasta las 4 de la tarde.\n\n- A las 16\'07 se reanuda la vista.\n\n- El Ministerio Fiscal solicita la lectura de:\n\n- Segunda declaraci\xc3\xb3n del Capit\xc3\xa1n de Artiller\xc3\xada D. Juan BATISTA GONZALEZ. Intervenci\xc3\xb3n del abogado defensor del Capit\xc3\xa1n BATISTA: pide se lea el encabezamiento \xc3\xadntegro de la declaraci\xc3\xb3n. El Presidente accedi\xc3\xb3 y se ley\xc3\xb3.\n- Testimonio del General D. Jos\xc3\xa9 JUSTE FERNANDEZ.\n- Certificado evacuando interrogatorio del General JUSTE.\n- Certificado declaraci\xc3\xb3n del General JUSTE.\n- Certificado declaraci\xc3\xb3n del General JUSTE.\n- Certificado declaraci\xc3\xb3n del General JUSTE.\n- Primera declaraci\xc3\xb3n del Capit\xc3\xa1n de Infanter\xc3\xada D. Francisco DUSMET GARCIA FIGUERAS.\n- Segunda declaraci\xc3\xb3n del Capit\xc3\xa1n DUSMET. Abogado defensor pide se lea el d\xc3\xada de la anterior declaraci\xc3\xb3n. El Presidente accede. La fecha no figura. Intervienen el Fiscal para aclarar los que asistieron a la declaraci\xc3\xb3n. El Presidente pregunta si es suficiente. El Defensor dice s\xc3\xad.\n- Primera declaraci\xc3\xb3n de Infanter\xc3\xada D. Carlos ALVAREZ ARENAS Y PARDINA.\n- Declaraci\xc3\xb3n indagatoria del Capit\xc3\xa1n ALVAREZ ARENAS.\n- Tercera declaraci\xc3\xb3n del Capit\xc3\xa1n ALVAREZ ARENAS.\n- Primera declaraci\xc3\xb3n del Capit\xc3\xa1n de Infanter\xc3\xada D. Jos\xc3\xa9 PASCUAL GALVEZ. El abogado pide el encabezamiento de la anterior declaraci\xc3\xb3n. El Presidente pide el porqu\xc3\xa9 y accede.\n- Declaraci\xc3\xb3n indagatoria del Capit\xc3\xa1n PASCUAL.\n- Informaci\xc3\xb3n de la fecha de procesamiento del Capit\xc3\xa1n PASCUAL. Enfrentamiento Fiscal-Defensor en torno a la fecha de detecci\xc3\xb3n del Capit\xc3\xa1n PASCUAL y la declaraci\xc3\xb3n.\n\n...//...\n\n- 3 -\n\n- El Ministerio Fiscal solicita la lectura de:\n- Primera declaraci\xc3\xb3n del Capit\xc3\xa1n de Intendencia D. Jos\xc3\xa9 CID FORTEA.\n- Declaraci\xc3\xb3n indagatoria del Capit\xc3\xa1n CID.\n- Primera declaraci\xc3\xb3n del Coronel de la Guardia Civil D. Miguel MANCHADO GARCIA.\n- Tercera declaraci\xc3\xb3n del Coronel MANCHADO.\n- Certificaci\xc3\xb3n del Teniente Coronel D. Antonio ROMERO SANCHEZ sobre salida del coche particular del Coronel MANCHADO\n\n- A las 17\'53 el PRESIDENTE DE LA SALA suspende la vista hasta ma\xc3\xb1ana a las 1000 horas.\n\n2.- INCIDENCIAS Y ESTIMACIONES SOBRE EL DESARROLLO DE LA SESION.\n\n- La sesi\xc3\xb3n empez\xc3\xb3 sin la presencia de tres defensores (Tcol. -- MEER, Sr. GOMEZ GARCIA, Sr. LI\xc3\x91AN), que se incorporaron posteriormente.\n\nEl C\xc3\xb3digo exige la presencia de los Defensores. Este hecho se estima grave, pues con base en \xc3\xa9l podr\xc3\xada alegarse nulidad. Hoy nadie apreci\xc3\xb3 esta irregularidad.\n\n- Durante la lectura de las diligencias que afectan al Capit\xc3\xa1n - DUSMET y Capit\xc3\xa1n PASCUAL, sus respectivos defensores han solicitado especificaciones sobre fechas y circunstancias en que fueron tomadas las mismas. El PRESIDENTE DE LA SALA ordena que as\xc3\xad se haga.\n\nDe las diligencias de hoy, para el p\xc3\xbablico asistente que no conoce con detalle el Sumario, ha podido apreciarse en versi\xc3\xb3n de los propios procesados lo siguiente:\n\n- Comandante CORTINA y Capit\xc3\xa1n GOMEZ IGLESIAS: niegan todo contacto o participaci\xc3\xb3n conspirativa con el resto de procesados.\n- Resto de los procesados: niegan su participaci\xc3\xb3n en conspiraci\xc3\xb3n alguna. Sus actuaciones fueron -seg\xc3\xban los procesados- motivadas por la obediencia debida a sus mandos, que aceptan do una decisi\xc3\xb3n de S.M., adoptaron las medidas necesarias para ejercer \xc3\xa9sta.\n\nDestaca en la lectura la exaltaci\xc3\xb3n de valores morales reali\n\n...//...\n\n- 4 -\n\nzada en sus respectivas declaraciones por el General TORRES ROJAS, el Coronel SAN MARTIN, y el Comandante PARDO.\n\nEl Coronel SAN MARTIN descarga su responsabilidad sobre el General JUSTE.\n\nEl Comandante PARDO en sus declaraciones exculpa a los Capitanes que considera sus subordinados.\n\n- Han sido leidas todas las certificaciones del General JUSTE, de las que se puede deducir: que no ten\xc3\xada conocimiento previo de los hechos; que el Coronel SAN MARTIN le ocult\xc3\xb3 los preparativos; que no se vi\xc3\xb3 privado del ejercicio del mando; y que cuando pudo trat\xc3\xb3 de confirmar la situaci\xc3\xb3n, obrando posteriormente en consecuencia.\n\n- En la sesi\xc3\xb3n de hoy:\n\n. Se ha hecho referencia concreta al Rey, S.M. \xc3\xb3 CORONA, no menos de 89 veces y a la REINA, no menos de 5 veces.\n\n. Se ha hecho referencia concreta al CESID, no menos de 21 veces.\n\n3.- OTROS HECHOS Y COMENTARIOS.\n\n- Entre asistentes ha circulado una copia de un escrito ""R\xc3\xa9plica al Sr. PEDRO RIUS"" firmado por el Codefensor Comandante de Infanter\xc3\xada BERLANGA REYES (Capit\xc3\xa1n BATISTA). Se ignora si ha sido entregado a la prensa.\n\n- Hoy no ha existido contacto entre m.c.s.-procesados.\n\n- Es previsible que aumente la tensi\xc3\xb3n entre familiares y periodistas que coincidan en descansos, por la irritaci\xc3\xb3n que les produce a los primeros algunas cr\xc3\xb3nicas.\n\n- Tambi\xc3\xa9n existe alguna irritaci\xc3\xb3n entre letrados y periodistas por el control de seguridad.\n\n- Ser\xc3\xada deseable la instalaci\xc3\xb3n de una ""consigna"" anterior al control donde depositar efectos (abrigos, bolsos, maletines - prensa, etc.).",Vista oral 281 del Consejo Supremo de Justicia Militar 22 de febrero de 1982.txt\nVista oral 2/81 del Consejo Supremo de Justicia Militar (24 de febrero de 1982).,https://23fbuscador.rtve.es/document/ocr/1858?page_size=200&page=1,5,"Resumen global del documento:\n\nEl documento narra el desarrollo tenso y conflictivo de una serie de sesiones del Consejo Supremo de Justicia Militar en febrero de 1982, marcadas por pol\xc3\xa9micas en torno a la cobertura medi\xc3\xa1tica del Diario 16 y la actitud de los procesados, defensores y fuerzas militar...","[\'C/SG/2992/24-02-82\', \'Vista Oral 2/81\', \'Consejo Supremo de Justicia Militar\']","C/SG/2992/24-02-82\n\n# NOTA INFORMATIVA\n\nASUNTO: Vista Oral 2/81. del Consejo Supremo de Justicia Militar.\n\n## 1.- DESARROLLO DE LA SESION CORRESPONDIENTE AL 23.02.82\n\nAntes de la hora de comienzo oficial de la Vista las comisiones militares y familias comentan el art\xc3\xadculo de Diario 16 ""As\xc3\xad -asaltamos el Parlamento"", escrito por Adolfo Salvador con la opini\xc3\xb3n un\xc3\xa1nime de su inoportunidad, pero sin que se detecte que ello pueda afectar el discurrir del Juicio.\n\nConforme pasa el tiempo y no comienza la sesi\xc3\xb3n los comentarios surgen, as\xc3\xad como el movimiento de periodistas.\n\nEl primer rumor es que los procesados se niegan a entrar en -la Sala con motivo del art\xc3\xadculo antes citado.\n\nDespu\xc3\xa9s la noticia es que los defensores tambi\xc3\xa9n se niegan a/entrar en la Sala.\n\nEn este tiempo el Tribunal est\xc3\xa1 sentado en sus sitios correspondientes. Surge a continuaci\xc3\xb3n la noticia de que se comenzar\xc3\xada/si hay una rectificaci\xc3\xb3n de la noticia.\n\nLlaman al director de Diario 16 y entra, al parecer, a hablar con el Tribunal. Esto se repite por lo menos tres veces.\n\nSe busca una soluci\xc3\xb3n negociada. El ambiente es de expectaci\xc3\xb3n-tensa. La \xc3\xbaltima noticia es que la condici\xc3\xb3n impuesta por los defensores es que tienen que suspender la acreditaci\xc3\xb3n a los periodistas de Diario 16.\n\nParece ser que los defensores se niegan, si no se dan estas -/ condiciones, a ejercer la defensa y se habla de que habr\xc3\xa1 que nombrar defensores de oficio. Un grupo de periodistas afirma que esto lo apoyan s\xc3\xb3lo tres o cuatro defensores y que el resta estar\xc3\xada dispuesto a cumplir con su obligaci\xc3\xb3n.\n\n- 2 -\n\nAnte la disyuntiva de que se aceptara la propuesta por parte del Tribunal, los representantes de TV. y RN. piensan que habr\xc3\xa1 solidaridad del resto de la prensa con los afectados. Tambi\xc3\xa9n son de la opini\xc3\xb3n que el tratamiento que P.J. Ram\xc3\xadrez est\xc3\xa1 dando al tema es de ""una gran frivolidad"".\n\nA las 13\'32 horas se abre la sesi\xc3\xb3n sin que la mayor\xc3\xada sepa/ qu\xc3\xa9 soluci\xc3\xb3n se adopt\xc3\xb3.\n\nA petici\xc3\xb3n de la Defensa (Sr. G\xc3\xb3mez Garc\xc3\xada), el Presidente - concede a \xc3\xa9ste la palabra:\n\nProtesta en\xc3\xa9rgica y en voz enaltecida por el agravio a su defendido. Al comenzar esta alocuci\xc3\xb3n un familiar de un procesado/ (mujer) dice en voz alta ""\xc2\xa1Bien!"".\n\nTermina y un Jefe de uniforme en voz alta profiere palabras/ malsonantes que son el inicio de aplausos de paisanos y algunos/ militares de uniforme.\n\nDespu\xc3\xa9s, el Fiscal, en uso de sus facultades toma la palabra y con energ\xc3\xada en las palabras y en la voz, hace las consideraciones que considera oportunas.\n\nUna vez terminado, el Sr. Scandell habla en nombre del General De Santiago e interpretando el sentido de todos los defensores militares, en su propia representaci\xc3\xb3n y sobre todo como militar. Su voz es igualmente en\xc3\xa9rgica.\n\nA continuaci\xc3\xb3n el Sr. Presidente suspende la acreditaci\xc3\xb3n de la representaci\xc3\xb3n de Diario 16. Su voz tambi\xc3\xa9n es en\xc3\xa9rgica.\n\nAqu\xc3\xad se lanzan palabras como ""bandido, bien, etc."". Fuertes/ aplausos de familiares y algunas personas de uniforme.\n\nCon los periodistas pertenecientes a Diario 16 salen tambi\xc3\xa9n Miguel \xc3\x81ngel Aguilar y dos periodistas m\xc3\xa1s. El resto se mira, ti-tubea, pero se queda.\n\nComienzan las lecturas de las declaraciones. La primera del/ Capit\xc3\xa1n de la Guardia Civil D. JOSE LUIS ABAD GUTIERREZ. Nada m\xc3\xa1s comenzar, el Sr. Pedrol Rius se levanta y sale de la Sala. Detr\xc3\xa1s de \xc3\xa9l un grupo de letrados que estaban a su alrededor y simult\xc3\xa1neamente la pr\xc3\xa1ctica totalidad de los periodistas. S\xc3\xb3lo quedan - nueve periodistas. A los cinco minutos entran dos periodistas.\n\n...///...\n\n- 3 -\n\nA las 13\'45 horas entra en la Sala el Sr. Pedrol Rius con los letrados y representantes acreditados que anteriormente le hab\xc3\xadan acompa\xc3\xb1ado en la salida. Pasados unos cinco minutos vuelve a salir el Sr. Pedrol Rius.\n\nA las 14\'00 horas entran dos periodistas, siendo uno de ellos de El Pa\xc3\xads. Otro sale.\n\nEn Anexo A, se adjuntan NOTAS INFORMATIVAS EXTRAORDINARIAS -/ NUMS. 1 y 2, elaboradas por la OIDREP.\n\nAl iniciarse propiamente la Sesi\xc3\xb3n, continu\xc3\xb3 el Sr. Fiscal solicitando la lectura de las siguientes diligencias:\n\n- 1\xc2\xaa y 3\xc2\xaa declaraciones del Capit\xc3\xa1n de la Guardia Civil Don JOSE LUIS ABAD GUTIERREZ.\n- Certificaci\xc3\xb3n parcial sobre servicios relativa al anterior.\n- 1\xc2\xaa declaraci\xc3\xb3n y declaraci\xc3\xb3n indagatoria del Capit\xc3\xa1n de la Guardia Civil Don ENRIQUE BOBIS GONZALEZ.\n- 1\xc2\xaa declaraci\xc3\xb3n y declaraci\xc3\xb3n indagatoria del Capit\xc3\xa1n de la Guardia Civil Don JUAN PEREZ DE LA LASTRA.\n\nA las 14\'15 horas el Presidente de la Sala suspende la Vista/ hasta las 16\'15 horas.\n\nPor la tarde el Sr. Fiscal solicit\xc3\xb3 la lectura de:\n\n- 1\xc2\xaa declaraci\xc3\xb3n y declaraci\xc3\xb3n indagatoria del Capit\xc3\xa1n de la Guardia Civil Don CARLOS LAZARO GORTAIN.\n- 1\xc2\xaa declaraci\xc3\xb3n del Teniente de la Guardia Civil Don MANUEL/ BOZA CARRANCO.\n- 1\xc2\xaa declaraci\xc3\xb3n del Teniente de la Guardia Civil Don PEDRO - IZQUIERDO SANCHEZ.\n- 1\xc2\xaa declaraci\xc3\xb3n del Teniente de la Guardia Civil Don JOSE NU\xc3\x91EZ RUANO.\n- 1\xc2\xaa declaraci\xc3\xb3n del Teniente de la Guardia Civil Don VICENTE RAMOS RUEDA.\n- 1\xc2\xaa declaraci\xc3\xb3n y declaraci\xc3\xb3n indagatoria del Capit\xc3\xa1n Don -/ FRANCISCO ACERA MARTIN.\n\n...//...\n\n- 1\xc2\xaa declaraci\xc3\xb3n del Teniente de la Guardia Civil Don SANTIAGO VECINO NU\xc3\x91EZ.\n- 1\xc2\xaa declaraci\xc3\xb3n y declaraci\xc3\xb3n indagatoria del Capit\xc3\xa1n de la Guardia Civil Don FRANCISCO IGNACIO ROMAN.\n- 1\xc2\xaa y 2\xc2\xaa declaraciones, declaraci\xc3\xb3n indagatoria, Auto de Procesamiento y 3\xc2\xaa declaraci\xc3\xb3n del Capit\xc3\xa1n de la Guardia Civil Don JESUS MU\xc3\x91ECAS AGUILAR.\n- 1\xc2\xaa declaraci\xc3\xb3n del Cabo 1\xc2\xaa de la Guar

In [ ]:
df = pd.read_csv('23f_scrappedDF.csv')

In [ ]:
df.head()

,title,url,pages,summary,tags,transcript,filename
0,Vista oral 2/81 del Consejo Supremo de Justici...,https://23fbuscador.rtve.es/document/ocr/1860?...,3,El juicio oral 2/81 celebrado en febrero de 19...,"['C/SG/2820/20-02-82', 'DTOR.', 'Vista oral 2/...",C/SG/2820/20-02-82\nDTOR.\n\nNOTA INFORMATIVA\...,Vista oral 281 del Consejo Supremo de Justicia...
1,Vista oral 2/81 del Consejo Supremo de Justici...,https://23fbuscador.rtve.es/document/ocr/1859?...,4,Resumen global del documento:\n\nEl documento ...,"['C/SG/2896/22-02-82', 'Vista oral 2/81', 'Con...",C/SG/2896/22-02-82\n\n# NOTA INFORMATIVA\n\nAS...,Vista oral 281 del Consejo Supremo de Justicia...
2,Vista oral 2/81 del Consejo Supremo de Justici...,https://23fbuscador.rtve.es/document/ocr/1858?...,5,Resumen global del documento:\n\nEl documento ...,"['C/SG/2992/24-02-82', 'Vista Oral 2/81', 'Con...",C/SG/2992/24-02-82\n\n# NOTA INFORMATIVA\n\nAS...,Vista oral 281 del Consejo Supremo de Justicia...
3,Vista oral 2/81 del Consejo Supremo de Justici...,https://23fbuscador.rtve.es/document/ocr/1857?...,6,El documento recoge el desarrollo de la sesión...,"['C/SG/3.081/25-02-82', 'Vista Oral 2/81', 'Co...",C/SG/3.081/25-02-82\n\n# NOTA INFORMATIVA\n\nA...,Vista oral 281 del Consejo Supremo de Justicia...
4,Vista oral 2/81 del Consejo Supremo de Justici...,https://23fbuscador.rtve.es/document/ocr/1856?...,6,Resumen global del documento sobre la sesión d...,"['C/SG/3.249/26-02-82', 'SG', 'Consejo Supremo...",C/SG/3.249/26-02-82\nSG\n\n# NOTA INFORMATIVA\...,Vista oral 281 del Consejo Supremo de Justicia...

In [ ]:
df.columns

Index(['title', 'url', 'pages', 'summary', 'tags', 'transcript', 'filename'], dtype='object')

In [ ]:
print(df['transcript'][0])

C/SG/2820/20-02-82
DTOR.

NOTA INFORMATIVA

ASUNTO: Vista oral 2/81

1.- DESARROLLO DE LA SESIÓN CORRESPONDIENTE AL 20-02-82

- Solo ha tenido lugar la sesión de la mañana. Empezó a las 10,06 horas.

- Durante la sesión han tenido lugar, a petición del Sr. Fiscal las declaraciones siguientes:

. Parcial de Teniente Coronel D. Luis Arana Lorite (Ayte. Gral. Lluch).

. Parcial de Teniente Coronel D. Manuel Miler Hidalgo (Ayte. Gral. Esquivias).

. 1ª, 2ª, 3ª y 4ª del Teniente Coronel TEJERO.

. Careo Teniente Coronel TEJERO - SR. CARRES.

- Descanso de 11,50 horas a 12,13 horas.

. Careo Teniente Coronel TEJERO - Capitán GOMEZ IGLESIAS

. Certificación del Presidente del Congreso Sr. LAVILLA.

. Certificación sobre la situación militar del TCOL.TEJERO.

. 1ª y 3ª del Coronel D. DIEGO IBAÑEZ INGLES

. Certificación del entonces Gobernador Civil de Valencia D.José María Fernández del Rio Fernández

. 1ª y 3ª del Teniente Coronel MAS OLIVER.

La vista se interrumpió hasta las 10,00 horas del lunes día 22-02-82.

-1-

./.

2.- INCIDENCIAS E IMPRESIONES EN TORNO AL DESARROLLO DE LA SESION.

- Al finalizar la lectura de la segunda declaración del Coronel Ibañez el defensor del Gral. Armada hizo notar que se había omitido parte de la declaración; el presidente accedió a que se leyera lo omitido.

- El fiscal continúa pidiendo se lean declaraciones parciales. Al parecer existía un acuerdo informal de la SALA para permitir la lectura parcial de diligencias, así como no solicitar la lectura de declaraciones de personas citadas como testigos a la vista oral.

Este último aspecto fué roto ayer por el Sr. Fiscal.

- Uno de los defensores manifiesta que habían llegado a una "especie de acuerdo", antes de comenzar la vista, según el cual ni el Ministerio Fiscal ni los defensores iban a pedir excesivas lecturas de declaraciones. Sin embargo la línea del Fiscal está alargando de manera muy notable ésta fase inicial de la vista; puede dar lugar además a que algunos defensores hagan lo mismo.

- Reticencias y sonrisas de defensores y codefensores al leer se las declaraciones:

. Gobernador Civil de Valencia
. Teniente Coronel Tejero

- Continúa invocándose el protagonismo del REY y paralelamente el de la REINA; se afirma tenían conocimiento de lo que se proponían realizar los procesados. La lectura de declaraciones de algunos procesados hace que el nombre de Su Majestad esté presente de modo continuado. En quienes no tengan un juicio formado al respecto, introduce la duda en torno a la conducta del REY.

-2-
./.

- El CESID permanece en primera fila de declaraciones, con una nueva figura: el SECTOR DE VALENCIA.
En la cuarta declaración del Teniente Coronel TEJERO afirma que había más personas del CESID implicadas.

3.- OTRAS INFORMACIONES DE CARACTER GENERAL
- Los familiares ván tomando más actividad y se acercan más a las primeras filas. También realizan gestos y comentarios.
- Comentario entre letrados invitados sobre que está perfilada una misma línea defensiva que comprende al Gral. Armada, Cte. Cortina y Cap. Gómez Iglésias.
- Menor asistencia de invitados (Periodistas, familiares y asimismo militares).

PRENSA:
- Desde Barcelona ha llamado LA VANGUARDIA a la sala de prensa requiriendo información sobre qué decisión se adoptará en relación a los documentos que, al parecer, tiene el editor LARA (Supuesta maleta del Cap. Sánchez Valiente).

SEGURIDAD INTERIOR:
- La salida de los procesados al finalizar cada sesión, se ve alterada por la presencia de familiares y periodistas. Esta circunstancia, que puede dar lugar a incidentes, debería ser evitada.

SEGURIDAD EXTERIOR:
- Menos efectivos que en el día de ayer, al menos aparentemente, a lo largo del itinerario. Esta circunstancia se ha visto agravada por la no presencia de la Guardia Civil de Tráfico regulando la circulación en semáforos y giros obligados, sobre todo en la zona de Aluche a caballo sobre la carretera de Extremadura.